version: '3'

services:
  dashboard:
    build:
      context: .
    image: prafiles/user-analytics-dashboard:latest
    container_name: dashboard
    entrypoint: ["npm", "start"]
    ports:
    - "3000:3000"
    networks:
      analytics-dashboard:
        ipv4_address: 172.19.0.2
    depends_on:
    - "mongodb"

  dashboard-dev:
    image: prafiles/user-analytics-dashboard:latest
    container_name: dashboard-dev
    volumes:
    - .:/src
    working_dir: /src
    entrypoint: ["nodemon", "bin/www"]
    ports:
    - "3000:3000"
    networks:
      analytics-dashboard:
        ipv4_address: 172.19.0.3
    depends_on:
    - "mongodb"

  shell:
    tty: true
    stdin_open: true
    image: prafiles/user-analytics-dashboard:latest
    container_name: shell
    entrypoint: ["bash"]
    networks:
      analytics-dashboard:
        ipv4_address: 172.19.0.4


  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
    volumes:
    - dashboard-mongodb:/data/db
    ports:
    - 27017:27017
    networks:
      analytics-dashboard:
        ipv4_address: 172.19.0.5
    command: mongod --logpath=/dev/null # --quiet

volumes:
  dashboard-mongodb:
    external: true

networks:
  analytics-dashboard:
    external:
      name: analytics-dashboard